[supervisord]
nodaemon=true
logfile=/tmp/logs/supervisord.log
pidfile=/tmp/supervisord.pid
childlogdir=/tmp/logs
environment=STREAM_USER="%(ENV_STREAM_USER)s",STREAM_PASSWORD="%(ENV_STREAM_PASSWORD)s"

[program:xvfb]
command=/usr/bin/Xvfb :99 -screen 0 760x500x24 -ac -noreset +extension COMPOSITE +extension DAMAGE +extension GLX +extension RANDR +extension RENDER +extension MIT-SHM +extension XFIXES +extension XTEST
stdout_logfile=/tmp/logs/xvfb.log
stderr_logfile=/tmp/logs/xvfb.log
autorestart=true
priority=10
startsecs=2

[program:pulseaudio]
command=/docker/start-pulseaudio.sh
environment=HOME="/home/racer",XDG_RUNTIME_DIR="/tmp/runtime-racer",PULSE_RUNTIME_PATH="/tmp/runtime-racer/pulse",PULSE_SERVER="unix:/tmp/runtime-racer/pulse/native"
stdout_logfile=/tmp/logs/pulseaudio.log
stderr_logfile=/tmp/logs/pulseaudio.log
autorestart=true
priority=15
startsecs=2
startretries=10

[program:flash]
command=/docker/start-flash.sh
environment=DISPLAY=":99",HOME="/home/racer",XDG_RUNTIME_DIR="/tmp/runtime-racer",PULSE_RUNTIME_PATH="/tmp/runtime-racer/pulse",PULSE_SERVER="unix:/tmp/runtime-racer/pulse/native",PULSE_SINK="output",SDL_AUDIODRIVER="pulse"
stdout_logfile=/tmp/logs/flash.log
stderr_logfile=/tmp/logs/flash.log
autorestart=true
priority=20
startsecs=5

[program:selkies]
command=/docker/start-selkies.sh
environment=DISPLAY=":99",HOME="/home/racer",XDG_RUNTIME_DIR="/tmp/runtime-racer",PULSE_RUNTIME_PATH="/tmp/runtime-racer/pulse",PULSE_SERVER="unix:/tmp/runtime-racer/pulse/native",STREAM_USER="%(ENV_STREAM_USER)s",STREAM_PASSWORD="%(ENV_STREAM_PASSWORD)s"
stdout_logfile=/tmp/logs/selkies.log
stderr_logfile=/tmp/logs/selkies.log
autorestart=true
priority=30
startsecs=5
startretries=10
